server:
  port: 8082
  
spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://192.168.99.102:9411/

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://192.168.99.102:9090/eureka