server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:Satya
    driver-class-name: org.h2.Driver
    username: ibm
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
   
    trace-id128: true

  zipkin:
    base-url: http://192.168.99.102:9411/

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://192.168.99.102:9090/eureka
      
      
