
DROP TABLE IF EXISTS Factor;
 
CREATE TABLE Factor (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    COUNTRY_CODE VARCHAR(100) NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    CONVERSION_RATE DOUBLE NOT NULL,
    Brokercharges DOUBLE NOT NULL
);


INSERT INTO Factor (COUNTRY_CODE, COUNTRY_NAME, CONVERSION_RATE, Brokercharges) VALUES ('EUR', 'European Union', 83.4 , 2.1 );
INSERT INTO Factor (COUNTRY_CODE, COUNTRY_NAME, CONVERSION_RATE, Brokercharges) VALUES ('GBP', 'British Pound Sterling', 92.8 , 2.1 );
INSERT INTO Factor (COUNTRY_CODE, COUNTRY_NAME, CONVERSION_RATE, Brokercharges) VALUES ('SGD', 'Singapore Dollar', 53.4 , 1.5 );
INSERT INTO Factor (COUNTRY_CODE, COUNTRY_NAME, CONVERSION_RATE, Brokercharges) VALUES ('CNY', 'Chinese Yen', 10.5 , 1.1 );
  