server:
  port: 7777

spring:
  datasource:
    url: jdbc:h2:mem:Satya2
    driver-class-name: org.h2.Driver
    username: ibm
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true    
      
 
  