server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:Satya2
    driver-class-name: org.h2.Driver
    username: ibm
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka